---
- name: Install Docker and configure Docker Swarm
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt repository again
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker Swarm is already initialized
      command: docker info
      register: docker_info
      ignore_errors: yes

    - name: Initialize Docker Swarm on vm-1
      command: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: inventory_hostname == "vm-1" and (docker_info.rc != 0 or 'Swarm: active' not in docker_info.stdout)

    - name: Get join token for worker nodes
      command: docker swarm join-token worker -q
      register: join_token
      when: inventory_hostname == "vm-1"

    - name: Set join token fact
      set_fact:
        swarm_join_token: "{{ join_token.stdout }}"
      when: inventory_hostname == "vm-1"
    
    - name: Check if join token is available
      fail:
        msg: "Join token is not available. Ensure that the swarm is initialized on vm-1."
      when: inventory_hostname != "vm-1" and (join_token is not defined or join_token.stdout is not defined)

    - name: Join Docker Swarm as worker
      command: docker swarm join --token {{ swarm_join_token }} vm-1:2377
      when: inventory_hostname != "vm-1"

