---
- name: Установить Docker и настроить Docker Swarm
  hosts: all
  become: yes
  tasks:
    - name: Обновить репозиторий apt
      apt:
        update_cache: yes

    - name: Установить необходимые пакеты
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Добавить GPG-ключ Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить репозиторий Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Снова обновить репозиторий apt
      apt:
        update_cache: yes

    - name: Установить Docker
      apt:
        name: docker-ce
        state: present

    - name: Запустить службу Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Инициализировать Docker Swarm на vm-1
      command: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: inventory_hostname == "vm-1"

    - name: Получить токен для присоединения рабочих узлов
      command: docker swarm join-token worker -q
      register: join_token
      when: inventory_hostname == "vm-1"

    - name: Установить факт токена для всех узлов
      set_fact:
        join_token: "{{ join_token.stdout }}"
      when: inventory_hostname == "vm-1"

    - name: Присоединиться к Docker Swarm как рабочий узел
      command: docker swarm join --token {{ hostvars['vm-1'].join_token }} vm-1:2377
      when: inventory_hostname != "vm-1"

